# docker-compose.yml example

tor:
  image: dedimax/docker-tor-armhf-hidden-service
  links:
    - hello
    - world
  environment:
      PORT_MAP: 80 # Map port to detected service
  volumes:
    - ./keys:/var/lib/tor/hidden_service/

hello:
  image: hypriot/armhf-hello-world
  hostname: hello

world:
  image: hypriot/armhf-hello-world
  hostname: world
  
